/** Writes src/data/testimonials.ts from whatever is in public/testimonials. */
import sharp from 'sharp';
import { readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const DIR = 'public/testimonials';
const files = readdirSync(DIR).filter((f) => /\.jpe?g$/i.test(f)).sort();

const rows = [];
for (const f of files) {
  const { width, height } = await sharp(join(DIR, f)).metadata();
  rows.push(`  { src: '/testimonials/${f}', width: ${width}, height: ${height} },`);
}

writeFileSync(
  'src/data/testimonials.ts',
  `/**
 * Feedback from students of earlier cohorts.
 *
 * Screenshots, not transcribed text, because the screenshot is the proof — a
 * typed quote is something anyone can invent. The cost is that search engines
 * cannot read them, which is why the page around them carries the claim in
 * words.
 *
 * Every image is cropped above the chat header, so the sender's name and photo
 * are gone. The uncropped originals are kept out of public/ entirely — see
 * .gitignore. If you add more, run scripts/crop-testimonials.mjs first and
 * check the result before it ships: cropping removes the header, not a name
 * written inside a message.
 *
 * Generated by scripts/testimonials-data.mjs — re-run it after adding images.
 */

export interface Testimonial {
  src: string;
  width: number;
  height: number;
}

export const testimonials: Testimonial[] = [
${rows.join('\n')}
];
`,
  'utf8'
);

console.log(`كُتب src/data/testimonials.ts — ${rows.length} صورة`);
