/**
 * Feedback from students of earlier cohorts.
 *
 * Screenshots, not transcribed text, because the screenshot is the proof — a
 * typed quote is something anyone can invent. The cost is that search engines
 * cannot read them, which is why the page around them carries the claim in
 * words.
 *
 * Every image is cropped above the chat header, so the sender's name and photo
 * are gone. The uncropped originals are kept out of public/ entirely — see
 * .gitignore. If you add more, run scripts/crop-testimonials.mjs first and
 * check the result before it ships: cropping removes the header, not a name
 * written inside a message.
 *
 * Generated by scripts/testimonials-data.mjs — re-run it after adding images.
 */

export interface Testimonial {
  src: string;
  width: number;
  height: number;
}

export const testimonials: Testimonial[] = [
  { src: '/testimonials/feedback-01.jpg', width: 640, height: 1135 },
  { src: '/testimonials/feedback-02.jpg', width: 945, height: 1822 },
  { src: '/testimonials/feedback-03.jpg', width: 640, height: 1231 },
  { src: '/testimonials/feedback-04.jpg', width: 640, height: 1234 },
  { src: '/testimonials/feedback-05.jpg', width: 519, height: 960 },
  { src: '/testimonials/feedback-06.jpg', width: 640, height: 1234 },
  { src: '/testimonials/feedback-07.jpg', width: 545, height: 960 },
  { src: '/testimonials/feedback-08.jpg', width: 930, height: 960 },
  { src: '/testimonials/feedback-09.jpg', width: 640, height: 1233 },
  { src: '/testimonials/feedback-10.jpg', width: 640, height: 1233 },
  { src: '/testimonials/feedback-11.jpg', width: 499, height: 960 },
  { src: '/testimonials/feedback-12.jpg', width: 640, height: 1232 },
  { src: '/testimonials/feedback-13.jpg', width: 945, height: 1752 },
  { src: '/testimonials/feedback-14.jpg', width: 945, height: 1823 },
  { src: '/testimonials/feedback-15.jpg', width: 945, height: 1820 },
  { src: '/testimonials/feedback-16.jpg', width: 945, height: 1823 },
  { src: '/testimonials/feedback-17.jpg', width: 946, height: 2001 },
  { src: '/testimonials/feedback-18.jpg', width: 945, height: 1845 },
  { src: '/testimonials/feedback-19.jpg', width: 945, height: 1822 },
  { src: '/testimonials/feedback-20.jpg', width: 945, height: 1822 },
  { src: '/testimonials/feedback-21.jpg', width: 945, height: 1821 },
  { src: '/testimonials/feedback-22.jpg', width: 945, height: 1822 },
  { src: '/testimonials/feedback-23.jpg', width: 945, height: 1821 },
  { src: '/testimonials/feedback-24.jpg', width: 945, height: 1822 },
  { src: '/testimonials/feedback-25.jpg', width: 945, height: 1822 },
  { src: '/testimonials/feedback-26.jpg', width: 945, height: 1822 },
  { src: '/testimonials/feedback-27.jpg', width: 530, height: 960 },
  { src: '/testimonials/feedback-28.jpg', width: 945, height: 1883 },
  { src: '/testimonials/feedback-29.jpg', width: 483, height: 960 },
  { src: '/testimonials/feedback-30.jpg', width: 640, height: 1276 },
  { src: '/testimonials/feedback-31.jpg', width: 922, height: 1836 },
  { src: '/testimonials/feedback-32.jpg', width: 945, height: 1884 },
  { src: '/testimonials/feedback-33.jpg', width: 945, height: 1611 },
  { src: '/testimonials/feedback-34.jpg', width: 1082, height: 1401 },
  { src: '/testimonials/feedback-35.jpg', width: 945, height: 1884 },
  { src: '/testimonials/feedback-36.jpg', width: 945, height: 1883 },
  { src: '/testimonials/feedback-37.jpg', width: 945, height: 1854 },
  { src: '/testimonials/feedback-38.jpg', width: 945, height: 1884 },
  { src: '/testimonials/feedback-39.jpg', width: 945, height: 1883 },
  { src: '/testimonials/feedback-40.jpg', width: 945, height: 1429 },
  { src: '/testimonials/feedback-41.jpg', width: 1080, height: 607 },
  { src: '/testimonials/feedback-42.jpg', width: 1080, height: 2400 },
  { src: '/testimonials/feedback-43.jpg', width: 945, height: 1046 },
];
